name: Pelican Builder and Upload to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: install flex theme
        run: |
          pelican-themes -i  theme/Flex-2.4.0     
      - name: Build the prod site
        run: |
          make publish
      - name: Deploy to Azure Blob Storage
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: 'output'
          container_name: '$web'
          connection_string: ${{ secrets.ConnectionString }}
          sync: true